[package]
name = "vanrijn"
version = "0.1.0"
authors = ["Matthew Gordon <matthew.scott.gordon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32"
quickcheck = "0.9"
quickcheck_macros = "0.8"

[dependencies.nalgebra]
version = "0.19"
features = ["arbitrary"]


[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
codegen-units = 1